/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-secondary-fixed": "#1f1a1a",
        "primary-container": "#c5a059",
        "primary-fixed": "#ffdea5",
        "outline-variant": "#d1c5b4",
        "on-primary-container": "#4e3700",
        "tertiary": "#5d5f5f",
        "secondary-fixed-dim": "#cec4c3",
        "primary": "#775a19",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e4e2e1",
        "on-tertiary-container": "#393b3b",
        "surface-dim": "#dcd9d9",
        "outline": "#7f7667",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "surface-container": "#f0eded",
        "on-primary-fixed": "#261900",
        "inverse-on-surface": "#f3f0f0",
        "on-tertiary": "#ffffff",
        "surface-tint": "#775a19",
        "error": "#ba1a1a",
        "inverse-primary": "#e9c176",
        "on-secondary-container": "#6a6361",
        "on-tertiary-fixed-variant": "#454747",
        "surface-container-highest": "#e4e2e1",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#1a1c1c",
        "on-background": "#1b1c1c",
        "background": "#fcf9f8",
        "primary-fixed-dim": "#e9c176",
        "error-container": "#ffdad6",
        "secondary": "#645d5b",
        "surface-container-high": "#eae7e7",
        "on-surface-variant": "#4e4639",
        "on-primary-fixed-variant": "#5d4201",
        "on-secondary-fixed-variant": "#4c4544",
        "on-secondary": "#ffffff",
        "inverse-surface": "#303030",
        "secondary-fixed": "#ebe0de",
        "tertiary-fixed": "#e2e2e2",
        "on-surface": "#1b1c1c",
        "tertiary-container": "#a4a5a5",
        "surface": "#fcf9f8",
        "tertiary-fixed-dim": "#c6c6c7",
        "secondary-container": "#ebe0de",
        "surface-container-low": "#f6f3f2"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-mobile": "20px",
        "base": "8px",
        "margin-desktop": "40px",
        "container-max": "1200px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "stack-sm": "12px",
        "gutter": "24px"
      },
      "fontFamily": {
        "display-lg": ["Playfair Display"],
        "body-lg": ["Inter"],
        "headline-lg": ["Playfair Display"],
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Playfair Display"],
        "label-md": ["Inter"],
        "label-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Playfair Display"],
        "headline-md": ["Playfair Display"]
      },
      "fontSize": {
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg-mobile": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
